name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: ChatGPT Code Review
        uses: cirolini/chatgpt-github-actions@v1.3
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          #openai_engine: "text-davinci-002" #optional
          #openai_temperature: 0.5 #optional
          #openai_max_tokens: 2048 #optional
          mode: patch # file or patch 
